[[targets]]
name = "nico-pico.com"
URL = "s3://nico-pico.com?region=us-east-1"

[[matchers]]
# Cache static assets for 20 years.
pattern = "^.+\\.(js|css|png|jpg|gif|png|webp|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true