[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/nickstagrm/"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/in/hellonickevans"

[social.params]
icon = "brand-linkedin"